In [3]:
import numpy as np

In [ ]:
body[:6, :]  # 6 first rows, all columns

In [ ]:
type(body)

In [ ]:
numpy.ndarray

In [ ]:
body.ndim

In [ ]:
body.shape

In [ ]:
body.shape[0]##Number of rows

In [ ]:
body.shape[1]##Number of columns

In [ ]:
np.array([
    [ 1,  2,  3,  4 ],
    [ 5,  6,  7,  8 ],
    [ 9, 10, 11, 12 ]
])##2 dimensional array

In [ ]:
np.array([ [1], [2], [3] ])#3 X 1 matrix

In [ ]:
np.array([ [1, 2, 3, 4] ]) #1 X 4 matrix

In [ ]:
np.repeat([[1, 2, 3]], 4, axis=0)# 4 rows 4 X 3 matrix

In [ ]:
np.repeat([[1], [2], [3], [4]], 3, axis=1) #repeat column wise

In [ ]:
#columns stack

In [ ]:
np.column_stack(([10, 20], [30, 40], [50, 60]))

In [ ]:
#row stack

In [ ]:
np.row_stack(([10, 20], [30, 40], [50, 60]))

In [ ]:
np.column_stack((
    np.row_stack(([10, 20], [30, 40], [50, 60])),
    [70, 80, 90]
))

In [1]:
#reshape

In [4]:
A = np.array([
    [ 1,  2,  3,  4 ],
    [ 5,  6,  7,  8 ],
    [ 9, 10, 11, 12 ]
])#3 X 4

In [ ]:
A.size  # total number of elements

In [ ]:
A.ravel()  # the underlying array

In [5]:
A.shape = (4, 3)  # a tuple of length 2
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
A.shape = (12, )  # a tuple of length 1
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
A.reshape(-1, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [10]:
A.shape =(-1, 6)
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [11]:
A = np.linspace(0, 2, 20, endpoint=False).reshape(4, -1)
A

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9]])

In [12]:
A.T  # transpose

array([[0. , 0.5, 1. , 1.5],
       [0.1, 0.6, 1.1, 1.6],
       [0.2, 0.7, 1.2, 1.7],
       [0.3, 0.8, 1.3, 1.8],
       [0.4, 0.9, 1.4, 1.9]])